### ISSUE TITLE
Dotnet 6 support

### ISSUE THREAD

**Issue by anmo13** [Kieranties/SimpleVersion#150]
## Description
We're currently on an environment that supports both dotnet 3.1 and 6.0. If a developer doesn't have dotnet 3.1 installed at all. 

## Proposed Solution
Could we add a second targetframework for .net 6.0 please to support the newer dotnet version? 
## Test Cases
no specific testing

**Comment by asci13** [comment]
@Kieranties I could file a PR for multiple frameworks on the tools package, if you'd like. Would be nice to move to .net 6.0 so that folks don't need to have .net 3.1 installed to run simpleversion.

**Comment by Kieranties** [comment]
So sorry for not getting back to you sooner on this.  I've completed the upgrade, moved to new acceptance tests images and will have published shortly!

**Comment by asci13** [comment]
Awesome, thanks a lot! Switching to the new version as soon as i've run a few preliminary tests
